workspace:
  base: /go
  path: src/github.com/jmccann/drone-artifactory-cache

pipeline:
  build:
    image: golang:1.7
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -cover $(go list ./... | grep -v /vendor/)
      - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a
